source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'

target 'IDVSample' do
  use_frameworks!

  pod 'IDVSDK', '~> 3.1'

  pod 'IDVFaceSDK', '~> 3.1'
  pod 'FaceCoreBasic', '~> 7.2'

  pod 'IDVDocumentReader', '~> 3.1'
  pod 'DocumentReaderFullAuthRFID', '~> 8.2'


end
