source 'https://github.com/regulaforensics/podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'

target 'IDVSample' do
  use_frameworks!

  pod 'IDVSDK', '~> 3.8.0'

  pod 'IDVFaceSDK', '~> 3.8.0'
  pod 'FaceSDK', '~> 8.2.0'
  pod 'FaceCoreBasic', '~> 8.2.0'

  pod 'IDVDocumentReader', '~> 3.8.0'
  pod 'DocumentReader', '~> 9.6.0'
  pod 'DocumentReaderFullAuthRFID', '~> 9.6.0'

end
